version: '3'
services:
  app:
    container_name: conFusion
    restart: always
    build: .
    ports:
      - '3443:3443'
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'



